PosForRestaurant/Controllers/SalesRegisterController.cs
using AutoMapper;
using POS.BLL.ManagerRepositories;
using POS.Models.EntityModels;
using PosForRestaurant.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PosForRestaurant.Controllers
{
    public class SalesRegisterController : Controller
    {
		// GET: SalesRegister
		ItemCategoryManager _itemCategoryManager = new ItemCategoryManager();
		ItemManager _itemManager = new ItemManager();
		SellManager _sellManager = new SellManager();
		SellDetailsManager _sellDetailsManager = new SellDetailsManager();

		public ActionResult Terminal()
        {
			var model = new TerminalVM();
			model.ItemCategories = _itemCategoryManager.GetAll();
			model.Items = _itemManager.GetAll();
            return View(model);
        }

		[HttpPost]
		public ActionResult Terminal(TerminalVM model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					var terminal = Mapper.Map<Sell>(model);
					bool isSaved = _sellManager.Save(terminal);
					if (isSaved)
					{
						return RedirectToAction("Payment");
					}
				}
			}
			catch (Exception exception)
			{
				ModelState.AddModelError("", exception.Message);
				model.ItemCategories = _itemCategoryManager.GetAll();
				model.Items = _itemManager.GetAll();
				return View(model);
			}
			model.ItemCategories = _itemCategoryManager.GetAll();
			model.Items = _itemManager.GetAll();
			return View(model);
		}

		public ActionResult Payment()
		{
			var sellItem = _sellManager.GetLastOrDefault(m => m.Id == m.Id);
			var model = Mapper.Map<TerminalVM>(sellItem);
			return View(model);
		}

		[HttpPost]
		public ActionResult Payment(TerminalVM model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					var terminal = Mapper.Map<Sell>(model);
					
					bool isSaved = _sellManager.Update(terminal);
					if (isSaved)
					{
						int id = terminal.Id;
						return RedirectToAction("Receit", new { id });
					}
				}
			}
			catch (Exception exception)
			{
				ModelState.AddModelError("", exception.Message);
				var sell = _sellManager.GetLastOrDefault(m => m.Id == m.Id);
				model = Mapper.Map<TerminalVM>(sell);
				return View(model);
			}
			return View(model);
		}

		public ActionResult Receit(int id)
		{
			var sellItem = _sellManager.GetById(id);
			var model = Mapper.Map<TerminalVM>(sellItem);
			model.SellDetailses = _sellDetailsManager.Get(m => m.SellId == id);
			return View(model);
		}
	}

	
}

PosForRestaurant/Controllers/StockListController.cs
using AutoMapper;
using POS.BLL.ManagerRepositories;
using POS.Models.EntityModels;
using PosForRestaurant.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace PosForRestaurant.Controllers
{
    public class StockListController : Controller
    {
		ItemCategoryManager _ItemCategoryManager = new ItemCategoryManager();
		ItemManager _itemManager = new ItemManager();
        // GET: StockList
        public ActionResult ItemList()
        {
			var model = _itemManager.GetAll();

			return View(model);
		}

		public ActionResult AddCategory()
		{
			var model = new ItemCategoryCreateVM();
			model.ItemCategories = _ItemCategoryManager.GetAll();
			return View(model);
		}

		[HttpPost]
		public ActionResult AddCategory(ItemCategoryCreateVM model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					var itemCategory = Mapper.Map<ItemCategory>(model);
					bool isSaved = _ItemCategoryManager.Save(itemCategory);
					if (isSaved)
					{
						return RedirectToAction("AddCategory");
					}
				}
			}
			catch (Exception exception)
			{
				ModelState.AddModelError("", exception.Message);
				model.ItemCategories = _ItemCategoryManager.GetAll();
				return View(model);
			}
			model.ItemCategories = _ItemCategoryManager.GetAll();
			return View(model);

		}

		public ActionResult AddItem()
		{
			var model = new ItemCreateVM();
			model.ItemCategories = _ItemCategoryManager.GetAll();
			return View(model);
		}


		// POST: Item/Create
		[HttpPost]
		public ActionResult AddItem(ItemCreateVM model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					using (var binaryReader = new BinaryReader(model.ImageUpload.InputStream))
					{
						model.Image = binaryReader.ReadBytes(model.ImageUpload.ContentLength);
					}

					var item = Mapper.Map<Item>(model);

					bool isSaved = _itemManager.Save(item);
					if (isSaved)
					{
						return RedirectToAction("AddItem");
					}
				}

			}
			catch(Exception exception)
			{
				ModelState.AddModelError("", exception.Message);
				model.ItemCategories = _ItemCategoryManager.GetAll();
				return View(model);
			}
			model.ItemCategories = _ItemCategoryManager.GetAll();
			return View(model);

		}


		public ActionResult ItemDetailsView(int id)
		{
			var item = _itemManager.GetById(id);
			var model = Mapper.Map<ItemCreateVM>(item);
			var base64 = Convert.ToBase64String(item.Image);
			var imgsrc = string.Format("data:image/png;base64,{0}", base64);

			//model.ImageUpload = imgsrc;
			
			model.ItemCategories = _ItemCategoryManager.GetAll();
			return View(model);
		}


		[HttpPost]
		public ActionResult ItemDetailsView(ItemCreateVM model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					if(model.ImageUpload != null)
					{
						using (var binaryReader = new BinaryReader(model.ImageUpload.InputStream))
						{
							model.Image = binaryReader.ReadBytes(model.ImageUpload.ContentLength);
						}
					}

					var item = Mapper.Map<Item>(model);

					bool isSaved = _itemManager.Update(item);
					if (isSaved)
					{
						return RedirectToAction("ItemList");
					}
				}

			}
			catch (Exception exception)
			{
				ModelState.AddModelError("", exception.Message);
				model.ItemCategories = _ItemCategoryManager.GetAll();
				return View(model);
			}
			model.ItemCategories = _ItemCategoryManager.GetAll();
			return View(model);
		}

		public ActionResult DeleteItem(int id)
		{
			var item = _itemManager.GetById(id);
			var model = Mapper.Map<ItemCreateVM>(item);
			try
			{
					bool isDeleted = _itemManager.Remove(item);
					if (isDeleted)
					{
						return RedirectToAction("ItemList");
					}
			}
			catch (Exception exception)
			{
				ModelState.AddModelError("", exception.Message);
				model.ItemCategories = _ItemCategoryManager.GetAll();
				return View("ItemDetailsView", model);
			}
			model.ItemCategories = _ItemCategoryManager.GetAll();
			return View("ItemDetailsView", model);
		}

		public JsonResult DeleteCategory(ItemCategory categoryId)
		{
			if (categoryId == null)
			{
				return null;
			}

			bool Result = _ItemCategoryManager.Remove(categoryId);

			return Json(Result);
		} 

		public JsonResult GetItemList(int id)
		{
			var item = _itemManager.GetById(id);
			return Json(item);
		}


	}
}

PosForRestaurant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - POS for Restaurant</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>

	<div style="border:1px groove grey; height:450px;" class="container body-content">
		@RenderBody()
	</div>
	<hr />
	<footer>
		<p>&copy; @DateTime.Now.Year - Refat Bin Mustaque</p>
	</footer>

	<script src="~/Scripts/jquery-1.10.2.min.js"></script>
	<script src="~/Scripts/bootstrap.min.js"></script>
	<script src="~/Scripts/jquery.validate.min.js"></script>
	<script src="~/Scripts/jquery.validate.js"></script>
	<script src="~/Scripts/jquery.validate-vsdoc.js"></script>
	@RenderSection("scripts", false);
</body>
</html>

PosForRestaurant/Views/Shared/_SalesRegisterLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - POS for Restaurant</title>
	<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
	<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body style="">
	@{
		var pageName = ViewContext.RouteData.Values["action"].ToString();
	}

	<div class="container" style="color:black;">
		<ul class="nav nav-tabs">
			@if (pageName == "Terminal")
			{
				<li class="@(pageName == "Terminal" ? "active" : "")" id="TerminalTab">@Html.ActionLink("Terminal", "Terminal", "SalesRegister")</li>
			}
			else if (pageName == "Payment")
			{
				<li class="@(pageName == "Payment" ? "active" : "")" id="PaymentTab">Payment</li>
			}
			else
			{
				<li class="@(pageName == "Payment" ? "active" : "")" id="PaymentTab">Print Receit</li>
			}

		</ul>
		<div style="border:1px groove grey; height:450px;" class="container body-content ">
			@RenderBody()
		</div>

		<hr />
		<a href="@Url.Action("Index", "Home")">
			<button class="btn btn-default pull-right">
				Home Menu
			</button>
		</a>
		<footer>
			<p>&copy; @DateTime.Now.Year - Refat Bin Mustaque</p>
		</footer>
	</div>

	<script src="~/Scripts/jquery-1.10.2.min.js"></script>
	<script src="~/Scripts/bootstrap.min.js"></script>
	<script src="~/Scripts/jquery.validate.min.js"></script>
	<script src="~/Scripts/jquery.validate.js"></script>
	<script src="~/Scripts/jquery.validate-vsdoc.js"></script>

	@RenderSection("scripts", false);
</body>
</html>

PosForRestaurant/Views/Shared/_SettingLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - POS for Restaurant</title>
	<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
	<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body style="">
	@{
		var pageName = ViewContext.RouteData.Values["action"].ToString();
	}

	<div class="container" style="color:black;">
		<ul class="nav nav-tabs">
				<li class="@(pageName == "TableZone" ? "active" : "")" id="TerminalTab">@Html.ActionLink("Terminal", "Terminal", "SalesRegister")</li>
		</ul>
		<div style="border:1px groove grey; height:450px;" class="container body-content ">
			@RenderBody()
		</div>

		<hr />
		<a href="@Url.Action("Index", "Home")">
			<button class="btn btn-default pull-right">
				Home Menu
			</button>
		</a>
		<footer>
			<p>&copy; @DateTime.Now.Year - Refat Bin Mustaque</p>
		</footer>
	</div>

	<script src="~/Scripts/jquery-1.10.2.min.js"></script>
	<script src="~/Scripts/bootstrap.min.js"></script>
	<script src="~/Scripts/jquery.validate.min.js"></script>
	<script src="~/Scripts/jquery.validate.js"></script>
	<script src="~/Scripts/jquery.validate-vsdoc.js"></script>

	@RenderSection("scripts", false);
</body>
</html>

PosForRestaurant/Views/Shared/_StockListLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - POS for Restaurant</title>
	<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
	<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body style="">
	@{
		var pageName = ViewContext.RouteData.Values["action"].ToString();
	}

	<div class="container body-content" style="color:black;">
		<ul class="nav nav-tabs">
			@if (pageName == "ItemDetailsView")
			{
				<li class="@(pageName == "ItemList" ? "active" : "")" id="ItemListTab">@Html.ActionLink("Item List", "ItemList", "StockList")</li>
				<li class="@(pageName == "ItemDetailsView" ? "active" : "")" id="ItemDetailsViewTab">@Html.ActionLink("Item Details View", "ItemDetailsView", "StockList")</li>
				<li class="@(pageName == "AddCategory" ? "active" : "")" id="AddCategoryTab">@Html.ActionLink("Add Category", "AddCategory", "StockList")</li>
			}
			else
			{
				<li class="@(pageName == "ItemList" ? "active" : "")" id="ItemListTab">@Html.ActionLink("Item List", "ItemList", "StockList")</li>
				<li class="@(pageName == "AddItem" ? "active" : "")" id="AddItemTab">@Html.ActionLink("Add Item", "AddItem", "StockList")</li>
				<li class="@(pageName == "AddCategory" ? "active" : "")" id="AddCategoryTab">@Html.ActionLink("Add Category", "AddCategory", "StockList")</li>
			}

		</ul>
		<div style="border:1px groove grey; height:450px;" class="container body-content">
			@RenderBody()
		</div>

		<hr />
		<a href="@Url.Action("Index", "Home")">
			<button class="btn btn-default pull-right">
				Home Menu
			</button>
		</a>
		<footer>
			<p>&copy; @DateTime.Now.Year - Refat Bin Mustaque</p>
		</footer>
	</div>

	<script src="~/Scripts/jquery-1.10.2.min.js"></script>
	<script src="~/Scripts/bootstrap.min.js"></script>
	<script src="~/Scripts/jquery.validate.min.js"></script>
	<script src="~/Scripts/jquery.validate.js"></script>
	<script src="~/Scripts/jquery.validate-vsdoc.js"></script>
	@RenderSection("scripts", false);
</body>
</html>